### ISSUE TITLE
買い物リスト管理機能の実装

### ISSUE THREAD

**Issue by kamesan1577** [kamesan1577/tdd-demo#1]
## Description
シンプルな買い物リスト管理機能を作成します。以下の機能を実装します：

アイテムを買い物リストに追加する
アイテムを買い物リストから削除する
買い物リスト内のアイテムを表示する
買い物リスト内のアイテム数を取得する
## AI Summary
この買い物リスト管理機能に対しては、TDDの原則に従い、先にテストを記述してから機能を実装し、リファクタリングを行うべきです。要件を満たすためのクラスShoppingListのシグネチャは以下の通りです。

```mermaid
classDiagram
    class ShoppingList {
        +add_item(item: str)
        +remove_item(item: str)
        +get_items() -> List[str]
        +get_item_count() -> int
    }
```
## Todos
- [ ] ShoppingListクラスのadd_itemメソッドをテストするため、アイテムを追加した後にget_itemsがそのアイテムを返すことを確認するテストケースを作成する。
- [ ] ShoppingListクラスのremove_itemメソッドをテストするため、アイテムを削除した後にget_itemsがそのアイテムを返さないことを確認するテストケースを作成する。
- [ ] ShoppingListクラスのget_itemsメソッドをテストするため、初期状態では空のリストが返されることを確認するテストケースを作成する。
- [ ] ShoppingListクラスのget_item_countメソッドをテストするため、初期状態では0が返されることを確認するテストケースを作成する。
- [ ] 異常系テストとして、remove_itemで削除対象が存在しない場合の動作を確認するテストケースを作成する。
- [ ] add_itemメソッドにnullや空の文字列を渡した場合の挙動をテストするテストケースを作成する。
- [ ] テスト
