### ISSUE TITLE
買い物リスト機能の作成

### ISSUE THREAD

**Issue by TofuMasume** [kamesan1577/tdd-demo#2]
## アプリケーション仕様
シンプルな買い物リストアプリケーションを作成します。以下の機能を実装します：

- アイテムを買い物リストに追加する
- アイテムを買い物リストから削除する
- 買い物リスト内のアイテムを表示する
- 買い物リスト内のアイテム数を取得する

## AI Summary
本アプリケーションでは、買い物リスト機能のテストを行います。TDDの原則に従い、まずはテストを書いてから実装し、その後リファクタリングを行います。最初のステップとして、ShoppingListクラスに必要なメソッドのシグネチャを定義します。
## Todos
- [x] ShoppingListクラスを作成し、add_item(item)メソッドを定義する
- [x] add_itemメソッドに対するユニットテストを作成し、アイテムがリストに正しく追加されることを確認する
- [x] ShoppingListクラスにremove_item(item)メソッドを定義する
- [x] remove_itemメソッドに対するユニットテストを作成し、アイテムがリストから正しく削除されることを確認する
- [x] ShoppingListクラスにget_items()メソッドを定義する
- [x] get_itemsメソッドに対するユニットテストを作成し、リスト内のアイテムが正しく表示されることを確認する
- [x] ShoppingListクラスにget_item_count()メソッドを定義する
- [x] get_item_countメソッドに対するユニットテストを作成し、アイテム数が正しく取得できることを確認する
