### ISSUE TITLE
買い物リスト機能の実装

### ISSUE THREAD

**Issue by kamesan1577** [kamesan1577/tdd-demo#3]
## Description
シンプルな買い物リスト管理機能を作成します。以下の機能を実装します：

アイテムを買い物リストに追加する
アイテムを買い物リストから削除する
買い物リスト内のアイテムを表示する
買い物リスト内のアイテム数を取得する
## AI Summary
シンプルな買い物リスト管理機能の実装に関する要件。買い物リストモデルを作成し、アイテムの追加、削除、表示、カウント機能を実装する。テストは各機能に対して明確な期待値を持たせ、確認するために単体テストで行う。以下はクラス設計の概要です。 

```mermaid
classDiagram
    class ShoppingList {
        +add_item(item: str)
        +remove_item(item: str)
        +get_items(): list
        +get_item_count(): int
    }
```
## Todos
- [x] P1: [テスト] 買い物リストクラスの初期化が正しく行われることを確認するテストを作成する
- [ ] P1: [実装] ShoppingListクラスを作成し、初期化メソッドを実装する
- [ ] P1: [テスト] add_itemメソッドのテストを作成し、アイテム追加が成功するか確認する
- [ ] P2: [実装] add_itemメソッドを実装し、アイテムをリストに追加する機能を作成する
- [ ] P2: [テスト] remove_itemメソッドのテストを作成し、アイテム削除が成功するか確認する
- [ ] P2: [実装] remove_itemメソッドを実装し、アイテムをリストから削除する機能を作成する
- [ ] P2: [テスト] get_itemsメソッドのテストを作成し、現在のアイテムリストを表示するか確認する
- [ ] P2: [実装] get_itemsメソッドを実装し、リスト内のアイテムを返す機能を作成する
- [ ] P2: [テスト] get_item_countメソッドのテストを作成し、アイテム数が正しく返されるか確認する
- [ ] P2: [実装] get_item_countメソッドを実装し、リスト内のアイテム数を返す機能を作成する
